# Generated by Django 5.2 on 2026-07-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_auth', '0002_useraccount_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Institution Admin'), ('SUPERVISOR', 'Support Agent / Supervisor'), ('STANDARD', 'Customer / Standard User')], default='STANDARD', max_length=15),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
